// app/components/shopping-list/ShoppingListModal.tsx
'use client';

import { Dialog } from 'primereact/dialog';
import { Button } from 'primereact/button';
import { InputTextarea } from 'primereact/inputtextarea';
import { Toast } from 'primereact/toast';
import { useRef } from 'react';

interface ShoppingListModalProps {
  visible: boolean;
  shoppingList: string;
  onHide: () => void;
}

export default function ShoppingListModal({
  visible,
  shoppingList,
  onHide,
}: ShoppingListModalProps) {
  const toast = useRef<Toast>(null);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(shoppingList);
      toast.current?.show({
        severity: 'success',
        summary: 'Copied!',
        detail: 'Shopping list copied to clipboard',
        life: 3000,
      });
    } catch (err) {
      toast.current?.show({
        severity: 'error',
        summary: 'Error',
        detail: 'Failed to copy to clipboard',
        life: 3000,
      });
    }
  };

  const footer = (
    <div>
      <Button label="Close" icon="pi pi-times" onClick={onHide} severity="secondary" />
    </div>
  );

  return (
    <>
      <Dialog
        header="Shopping List"
        visible={visible}
        style={{ width: '600px' }}
        onHide={onHide}
        footer={footer}
        modal
        draggable={false}
        resizable={false}
      >
        <div>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              marginBottom: '1rem',
              padding: '0.75rem',
              background: '#eff6ff',
              borderRadius: '6px',
              color: '#1e40af',
            }}
          >
            <i className="pi pi-info-circle" />
            <span>Click the text area or the copy button below to copy your shopping list</span>
          </div>

          <InputTextarea
            value={shoppingList}
            rows={15}
            readOnly
            onClick={copyToClipboard}
            placeholder="Your shopping list will appear here..."
            style={{ width: '100%', fontFamily: 'monospace' }}
          />

          <div style={{ marginTop: '1rem' }}>
            <Button
              label="Copy to Clipboard"
              icon="pi pi-copy"
              onClick={copyToClipboard}
              severity="info"
              style={{ width: '100%' }}
            />
          </div>
        </div>
      </Dialog>

      <Toast ref={toast} position="top-right" />
    </>
  );
}

// src/app/components/shopping-list-modal/shopping-list-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DialogModule } from 'primeng/dialog';
import { ButtonModule } from 'primeng/button';
import { TextareaModule } from 'primeng/textarea';
import { ToastModule } from 'primeng/toast';
import { MessageService } from 'primeng/api';

@Component({
  selector: 'app-shopping-list-modal',
  templateUrl: './shopping-list-modal.component.html',
  styleUrl: './shopping-list-modal.component.css',
  standalone: true,
  imports: [CommonModule, DialogModule, ButtonModule, TextareaModule, ToastModule],
  providers: [MessageService]
})
export class ShoppingListModalComponent {
  @Input() visible: boolean = false;
  @Input() shoppingList: string = '';
  @Output() visibleChange = new EventEmitter<boolean>();

  constructor(private messageService: MessageService) {}

  onClose() {
    this.visible = false;
    this.visibleChange.emit(false);
  }

  async copyToClipboard() {
    try {
      await navigator.clipboard.writeText(this.shoppingList);
      this.messageService.add({
        severity: 'success',
        summary: 'Copied!',
        detail: 'Shopping list copied to clipboard',
        life: 3000
      });
    } catch (err) {
      // Fallback for browsers that don't support clipboard API
      this.fallbackCopyToClipboard();
    }
  }

  private fallbackCopyToClipboard() {
    const textArea = document.createElement('textarea');
    textArea.value = this.shoppingList;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    
    try {
      document.execCommand('copy');
      this.messageService.add({
        severity: 'success',
        summary: 'Copied!',
        detail: 'Shopping list copied to clipboard',
        life: 3000
      });
    } catch (err) {
      this.messageService.add({
        severity: 'error',
        summary: 'Copy Failed',
        detail: 'Unable to copy to clipboard',
        life: 3000
      });
    } finally {
      document.body.removeChild(textArea);
    }
  }
}
<p-dialog 
  [(visible)]="visible" 
  header="Shopping List" 
  [modal]="true" 
  [closable]="true"
  [draggable]="false"
  [resizable]="false"
  styleClass="shopping-list-modal-dialog"
  (onHide)="onClose()">
  
  <div class="shopping-list-content">
    <div class="copy-instructions">
      <i class="pi pi-info-circle"></i>
      <span>Click the text area below to copy your shopping list to clipboard</span>
    </div>
    
    <textarea 
      pTextarea 
      [value]="shoppingList" 
      rows="15"
      class="shopping-textarea"
      readonly
      (click)="copyToClipboard()"
      placeholder="Your shopping list will appear here...">
    </textarea>
    
    <div class="modal-actions">
      <button 
        pButton 
        type="button" 
        label="Copy to Clipboard" 
        (click)="copyToClipboard()"
        icon="pi pi-copy"
        severity="info"
        class="copy-button">
      </button>
    </div>
  </div>

  <ng-template pTemplate="footer">
    <div class="dialog-footer">
      <button 
        pButton 
        type="button" 
        label="Close" 
        (click)="onClose()"
        severity="secondary"
        icon="pi pi-times">
      </button>
    </div>
  </ng-template>
</p-dialog>

<p-toast position="top-right"></p-toast>
