// src/app/components/recipe-edit-modal/recipe-edit-modal.component.ts
import { Component, EventEmitter, Input, Output, OnChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DialogModule } from 'primeng/dialog';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { TextareaModule } from 'primeng/textarea';
import { DatePickerModule } from 'primeng/datepicker';
import { Recipe } from '../../services/recipe.service';

@Component({
  selector: 'app-recipe-edit-modal',
  templateUrl: './recipe-edit-modal.component.html',
  styleUrl: './recipe-edit-modal.component.css',
  standalone: true,
  imports: [CommonModule, FormsModule, DialogModule, ButtonModule, InputTextModule, TextareaModule, DatePickerModule]
})
export class RecipeEditModalComponent implements OnChanges {
  @Input() visible: boolean = false;
  @Input() recipe: Recipe | null = null;
  @Output() visibleChange = new EventEmitter<boolean>();
  @Output() recipeSaved = new EventEmitter<Recipe>();

  editedRecipe: Recipe = {
    id: '',
    name: '',
    type: '',
    cuisine: '',
    lastEaten: '',
    ingredients: [],
    url: ''
  };

  ingredientsText: string = '';
  lastEatenDate: Date | null = null;

  ngOnChanges() {
    console.log('Modal ngOnChanges - visible:', this.visible, 'recipe:', this.recipe?.name);
    if (this.recipe) {
      this.editedRecipe = { ...this.recipe };
      this.ingredientsText = Array.isArray(this.recipe.ingredients)
        ? this.recipe.ingredients.join('\n')
        : '';
      // Convert string date to Date object
      this.lastEatenDate = this.recipe.lastEaten ? new Date(this.recipe.lastEaten) : null;
    }
  }

  onCancel() {
    this.visible = false;
    this.visibleChange.emit(false);
  }

  onSave() {
    // Convert ingredients text back to array
    this.editedRecipe.ingredients = this.ingredientsText
      .split('\n')
      .map(ingredient => ingredient.trim())
      .filter(ingredient => ingredient.length > 0);

    // Convert Date object back to string
    if (this.lastEatenDate) {
      this.editedRecipe.lastEaten = this.lastEatenDate.toISOString();
    }

    this.recipeSaved.emit(this.editedRecipe);
    console.log('Recipe updated/saved', this.editedRecipe);

    this.visible = false;
    this.visibleChange.emit(false);
  }
}

<p-dialog 
  [(visible)]="visible" 
  header="Edit Recipe" 
  [modal]="true" 
  [closable]="true"
  [draggable]="false"
  [resizable]="false"
  styleClass="recipe-edit-dialog"
  (onHide)="onCancel()">
  
  <div class="recipe-form">
    <div class="form-field">
      <label for="name">Recipe Name</label>
      <input 
        id="name"
        type="text" 
        pInputText 
        [(ngModel)]="editedRecipe.name" 
        placeholder="Enter recipe name"
        class="form-input" />
    </div>

    <div class="form-row">
      <div class="form-field">
        <label for="type">Type</label>
        <input 
          id="type"
          type="text" 
          pInputText 
          [(ngModel)]="editedRecipe.type" 
          placeholder="e.g., Dinner, Breakfast"
          class="form-input" />
      </div>

      <div class="form-field">
        <label for="cuisine">Cuisine</label>
        <input 
          id="cuisine"
          type="text" 
          pInputText 
          [(ngModel)]="editedRecipe.cuisine" 
          placeholder="e.g., Italian, Mexican"
          class="form-input" />
      </div>
    </div>

    <div class="form-field">
      <label for="url">Recipe URL</label>
      <input 
        id="url"
        type="url" 
        pInputText 
        [(ngModel)]="editedRecipe.url" 
        placeholder="https://example.com/recipe"
        class="form-input" />
    </div>

    <div class="form-field">
      <label for="ingredients">Ingredients (one per line)</label>
      <textarea 
        id="ingredients"
        pInputTextarea 
        [(ngModel)]="ingredientsText" 
        rows="6"
        placeholder="Enter each ingredient on a new line&#10;Example:&#10;2 cups flour&#10;1 tsp salt&#10;3 eggs"
        class="form-textarea">
      </textarea>
    </div>

    <div class="form-field">
      <label for="lastEaten">Last Eaten</label>
      <p-datepicker
        id="lastEaten"
        [(ngModel)]="lastEatenDate"
        dateFormat="yy-mm-dd"
        [showIcon]="true"
        placeholder="Select date"
        styleClass="form-datepicker"
        appendTo="body">
      </p-datepicker>
    </div>
  </div>

  <ng-template pTemplate="footer">
    <div class="dialog-buttons">
      <button 
        pButton 
        type="button" 
        label="Cancel" 
        (click)="onCancel()"
        severity="secondary"
        icon="pi pi-times">
      </button>
      <button 
        pButton 
        type="button" 
        label="Save" 
        (click)="onSave()"
        severity="success"
        icon="pi pi-check">
      </button>
    </div>
  </ng-template>
</p-dialog>

// app/components/recipes/RecipeEditModal.tsx
'use client';

import { useState, useEffect } from 'react';
import { Dialog } from 'primereact/dialog';
import { Button } from 'primereact/button';
import { InputText } from 'primereact/inputtext';
import { InputTextarea } from 'primereact/inputtextarea';
import { Calendar } from 'primereact/calendar';
import { Recipe } from '../../types';

interface RecipeEditModalProps {
  recipe: Recipe;
  visible: boolean;
  onHide: () => void;
  onSave: (recipe: Recipe) => void;
}

export default function RecipeEditModal({ recipe, visible, onHide, onSave }: RecipeEditModalProps) {
  const [editedRecipe, setEditedRecipe] = useState<Recipe>(recipe);
  const [ingredientsText, setIngredientsText] = useState('');
  const [lastEatenDate, setLastEatenDate] = useState<Date | null>(null);

  useEffect(() => {
    if (recipe) {
      setEditedRecipe({ ...recipe });
      setIngredientsText(
        Array.isArray(recipe.ingredients) ? recipe.ingredients.join('\n') : ''
      );
      setLastEatenDate(recipe.lastEaten ? new Date(recipe.lastEaten) : null);
    }
  }, [recipe]);

  const handleSave = () => {
    const ingredients = ingredientsText
      .split('\n')
      .map((ingredient) => ingredient.trim())
      .filter((ingredient) => ingredient.length > 0);

    const lastEaten = lastEatenDate ? lastEatenDate.toISOString().split('T')[0] : '';

    onSave({ ...editedRecipe, ingredients, lastEaten });
    onHide();
  };

  const footer = (
    <div>
      <Button label="Cancel" icon="pi pi-times" onClick={onHide} severity="secondary" />
      <Button label="Save" icon="pi pi-check" onClick={handleSave} severity="success" />
    </div>
  );

  return (
    <Dialog
      header="Edit Recipe"
      visible={visible}
      style={{ width: '600px' }}
      onHide={onHide}
      footer={footer}
      modal
      draggable={false}
      resizable={false}
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <div>
          <label htmlFor="name" style={{ display: 'block', marginBottom: '0.5rem' }}>
            Recipe Name
          </label>
          <InputText
            id="name"
            value={editedRecipe.name}
            onChange={(e) => setEditedRecipe({ ...editedRecipe, name: e.target.value })}
            placeholder="Enter recipe name"
            style={{ width: '100%' }}
          />
        </div>

        <div style={{ display: 'flex', gap: '1rem' }}>
          <div style={{ flex: 1 }}>
            <label htmlFor="type" style={{ display: 'block', marginBottom: '0.5rem' }}>
              Type
            </label>
            <InputText
              id="type"
              value={editedRecipe.type}
              onChange={(e) => setEditedRecipe({ ...editedRecipe, type: e.target.value })}
              placeholder="e.g., Dinner, Breakfast"
              style={{ width: '100%' }}
            />
          </div>

          <div style={{ flex: 1 }}>
            <label htmlFor="cuisine" style={{ display: 'block', marginBottom: '0.5rem' }}>
              Cuisine
            </label>
            <InputText
              id="cuisine"
              value={editedRecipe.cuisine}
              onChange={(e) => setEditedRecipe({ ...editedRecipe, cuisine: e.target.value })}
              placeholder="e.g., Italian, Mexican"
              style={{ width: '100%' }}
            />
          </div>
        </div>

        <div>
          <label htmlFor="url" style={{ display: 'block', marginBottom: '0.5rem' }}>
            Recipe URL
          </label>
          <InputText
            id="url"
            type="url"
            value={editedRecipe.url}
            onChange={(e) => setEditedRecipe({ ...editedRecipe, url: e.target.value })}
            placeholder="https://example.com/recipe"
            style={{ width: '100%' }}
          />
        </div>

        <div>
          <label htmlFor="ingredients" style={{ display: 'block', marginBottom: '0.5rem' }}>
            Ingredients (one per line)
          </label>
          <InputTextarea
            id="ingredients"
            value={ingredientsText}
            onChange={(e) => setIngredientsText(e.target.value)}
            rows={6}
            placeholder="Enter each ingredient on a new line&#10;Example:&#10;2 cups flour&#10;1 tsp salt&#10;3 eggs"
            style={{ width: '100%' }}
          />
        </div>

        <div>
          <label htmlFor="lastEaten" style={{ display: 'block', marginBottom: '0.5rem' }}>
            Last Eaten
          </label>
          <Calendar
            id="lastEaten"
            value={lastEatenDate}
            onChange={(e) => setLastEatenDate(e.value as Date)}
            dateFormat="yy-mm-dd"
            showIcon
            placeholder="Select date"
            style={{ width: '100%' }}
          />
        </div>
      </div>
    </Dialog>
  );
}
