// app/components/recipes/IngredientsModal.tsx
'use client';

import { Dialog } from 'primereact/dialog';
import { Button } from 'primereact/button';
import { Recipe } from '../../types';

interface IngredientsModalProps {
  recipe: Recipe;
  visible: boolean;
  onHide: () => void;
}

export default function IngredientsModal({ recipe, visible, onHide }: IngredientsModalProps) {
  const footer = (
    <div>
      <Button label="Close" icon="pi pi-times" onClick={onHide} severity="secondary" />
    </div>
  );

  return (
    <Dialog
      header={`Ingredients - ${recipe?.name || 'Recipe'}`}
      visible={visible}
      style={{ width: '500px' }}
      onHide={onHide}
      footer={footer}
      modal
      draggable={false}
      resizable={false}
    >
      <div className="ingredients-content">
        {recipe && recipe.ingredients && recipe.ingredients.length > 0 ? (
          <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
            {recipe.ingredients.map((ingredient, index) => (
              <li
                key={index}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                  padding: '0.5rem 0',
                }}
              >
                <i className="pi pi-check-circle" style={{ color: '#10b981' }} />
                <span>{ingredient}</span>
              </li>
            ))}
          </ul>
        ) : (
          <div style={{ textAlign: 'center', padding: '2rem', color: '#6b7280' }}>
            <i className="pi pi-info-circle" style={{ fontSize: '2rem', marginBottom: '1rem' }} />
            <p>No ingredients listed for this recipe</p>
          </div>
        )}
      </div>
    </Dialog>
  );
}

// src/app/components/ingredients-modal/ingredients-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DialogModule } from 'primeng/dialog';
import { ButtonModule } from 'primeng/button';
import { Recipe } from '../../services/recipe.service';

@Component({
  selector: 'app-ingredients-modal',
  templateUrl: './ingredients-modal.component.html',
  styleUrl: './ingredients-modal.component.css',
  standalone: true,
  imports: [CommonModule, DialogModule, ButtonModule]
})
export class IngredientsModalComponent {
  @Input() visible: boolean = false;
  @Input() recipe: Recipe | null = null;
  @Output() visibleChange = new EventEmitter<boolean>();

  onClose() {
    this.visible = false;
    this.visibleChange.emit(false);
  }
}
<p-dialog 
  [(visible)]="visible" 
  [header]="'Ingredients - ' + (recipe?.name || 'Recipe')"
  [modal]="true" 
  [closable]="true"
  [draggable]="false"
  [resizable]="false"
  styleClass="ingredients-modal-dialog"
  (onHide)="onClose()">
  
  <div class="ingredients-content">
    @if (recipe && recipe.ingredients && recipe.ingredients.length > 0) {
      <ul class="ingredients-list">
        @for (ingredient of recipe.ingredients; track $index) {
          <li class="ingredient-item">
            <i class="pi pi-check-circle ingredient-icon"></i>
            <span>{{ ingredient }}</span>
          </li>
        }
      </ul>
    } @else {
      <div class="no-ingredients">
        <i class="pi pi-info-circle"></i>
        <p>No ingredients listed for this recipe</p>
      </div>
    }
  </div>

  <ng-template pTemplate="footer">
    <div class="dialog-footer">
      <button 
        pButton 
        type="button" 
        label="Close" 
        (click)="onClose()"
        severity="secondary"
        icon="pi pi-times">
      </button>
    </div>
  </ng-template>
</p-dialog>
