// src/app/components/grocery-add-modal/grocery-add-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DialogModule } from 'primeng/dialog';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { Select } from 'primeng/select';

@Component({
  selector: 'app-grocery-add-modal',
  templateUrl: './grocery-add-modal.component.html',
  styleUrl: './grocery-add-modal.component.css',
  standalone: true,
  imports: [CommonModule, FormsModule, DialogModule, ButtonModule, InputTextModule, Select]
})
export class GroceryAddModalComponent {
  @Input() visible: boolean = false;
  @Output() visibleChange = new EventEmitter<boolean>();
  @Output() itemAdded = new EventEmitter<{ name: string; type: string }>();

  newItem = {
    name: '',
    type: ''
  };

  typeOptions = [
    { label: 'Fruit', value: 'fruit' },
    { label: 'Vegetable', value: 'vegetable' },
    { label: 'Meat', value: 'meat' },
    { label: 'Home Goods', value: 'home goods' },
    { label: 'Grain', value: 'grain' },
    { label: 'Legume', value: 'legume' },
    { label: 'Nuts/Seeds', value: 'nuts/seeds' },
    { label: 'Condiments', value: 'condiments' },
    { label: 'Seafood', value: 'seafood' }
  ];

  onCancel() {
    this.resetForm();
    this.visible = false;
    this.visibleChange.emit(false);
  }

  onSave() {
    if (this.newItem.name.trim() && this.newItem.type) {
      this.itemAdded.emit({
        name: this.newItem.name.trim(),
        type: this.newItem.type
      });
      this.resetForm();
      this.visible = false;
      this.visibleChange.emit(false);
    }
  }

  resetForm() {
    this.newItem = {
      name: '',
      type: ''
    };
  }

  isFormValid(): boolean {
    return this.newItem.name.trim().length > 0 && this.newItem.type.length > 0;
  }
}

<p-dialog
  [(visible)]="visible"
  [modal]="true"
  [closable]="true"
  [draggable]="false"
  [resizable]="false"
  header="Add Grocery Item"
  [style]="{ width: '500px' }">

  <div class="form-container">
    <div class="form-field">
      <label for="itemName">Name</label>
      <input
        pInputText
        id="itemName"
        type="text"
        [(ngModel)]="newItem.name"
        placeholder="Enter item name"
        class="input-field" />
    </div>

    <div class="form-field">
      <label for="itemType">Type</label>
      <p-select
        id="itemType"
        [options]="typeOptions"
        [(ngModel)]="newItem.type"
        placeholder="Select type"
        appendTo="body"
        [scrollHeight]="'250px'"
        class="select-field">
      </p-select>
    </div>
  </div>

  <ng-template pTemplate="footer">
    <button
      pButton
      type="button"
      label="Cancel"
      (click)="onCancel()"
      severity="secondary"
      class="cancel-btn">
    </button>
    <button
      pButton
      type="button"
      label="Add Item"
      (click)="onSave()"
      [disabled]="!isFormValid()"
      severity="success"
      class="save-btn">
    </button>
  </ng-template>
</p-dialog>

// app/components/groceries/GroceryAddModal.tsx
'use client';

import { useState } from 'react';
import { Dialog } from 'primereact/dialog';
import { Button } from 'primereact/button';
import { InputText } from 'primereact/inputtext';
import { Dropdown } from 'primereact/dropdown';
import { GROCERY_TYPES } from '../../types';

interface GroceryAddModalProps {
  visible: boolean;
  onHide: () => void;
  onSave: (item: { name: string; type: string }) => void;
}

export default function GroceryAddModal({ visible, onHide, onSave }: GroceryAddModalProps) {
  const [newItem, setNewItem] = useState({ name: '', type: '' });

  const typeOptions = GROCERY_TYPES.map((type) => ({
    label: type,
    value: type.toLowerCase(),
  }));

  const handleSave = () => {
    if (newItem.name.trim() && newItem.type) {
      onSave({
        name: newItem.name.trim(),
        type: newItem.type,
      });
      resetForm();
      onHide();
    }
  };

  const handleCancel = () => {
    resetForm();
    onHide();
  };

  const resetForm = () => {
    setNewItem({ name: '', type: '' });
  };

  const isFormValid = () => {
    return newItem.name.trim().length > 0 && newItem.type.length > 0;
  };

  const footer = (
    <div>
      <Button label="Cancel" onClick={handleCancel} severity="secondary" />
      <Button
        label="Add Item"
        onClick={handleSave}
        disabled={!isFormValid()}
        severity="success"
      />
    </div>
  );

  return (
    <Dialog
      header="Add Grocery Item"
      visible={visible}
      style={{ width: '500px' }}
      onHide={handleCancel}
      footer={footer}
      modal
      draggable={false}
      resizable={false}
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <div>
          <label htmlFor="itemName" style={{ display: 'block', marginBottom: '0.5rem' }}>
            Name
          </label>
          <InputText
            id="itemName"
            value={newItem.name}
            onChange={(e) => setNewItem({ ...newItem, name: e.target.value })}
            placeholder="Enter item name"
            style={{ width: '100%' }}
          />
        </div>

        <div>
          <label htmlFor="itemType" style={{ display: 'block', marginBottom: '0.5rem' }}>
            Type
          </label>
          <Dropdown
            id="itemType"
            value={newItem.type}
            options={typeOptions}
            onChange={(e) => setNewItem({ ...newItem, type: e.value })}
            placeholder="Select type"
            style={{ width: '100%' }}
          />
        </div>
      </div>
    </Dialog>
  );
}
