// src/app/components/grocery-delete-modal/grocery-delete-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DialogModule } from 'primeng/dialog';
import { ButtonModule } from 'primeng/button';
import { GroceryItem } from '../../services/grocery.service';

@Component({
  selector: 'app-grocery-delete-modal',
  templateUrl: './grocery-delete-modal.component.html',
  styleUrl: './grocery-delete-modal.component.css',
  standalone: true,
  imports: [CommonModule, DialogModule, ButtonModule]
})
export class GroceryDeleteModalComponent {
  @Input() visible: boolean = false;
  @Input() grocery: GroceryItem | null = null;
  @Output() visibleChange = new EventEmitter<boolean>();
  @Output() confirmDelete = new EventEmitter<GroceryItem>();

  onCancel() {
    this.visible = false;
    this.visibleChange.emit(false);
  }

  onConfirm() {
    if (this.grocery) {
      this.confirmDelete.emit(this.grocery);
    }
    this.visible = false;
    this.visibleChange.emit(false);
  }
}

<p-dialog
  [(visible)]="visible"
  [modal]="true"
  [closable]="true"
  [draggable]="false"
  [resizable]="false"
  header="Confirm Delete"
  [style]="{ width: '400px' }">

  <div class="delete-confirmation">
    <p>Are you sure you want to delete <strong>{{ grocery?.name }}</strong>?</p>
    <p class="warning-text">This action cannot be undone.</p>
  </div>

  <ng-template pTemplate="footer">
    <button
      pButton
      type="button"
      label="Cancel"
      (click)="onCancel()"
      severity="secondary"
      class="cancel-btn">
    </button>
    <button
      pButton
      type="button"
      label="Delete"
      (click)="onConfirm()"
      severity="danger"
      class="confirm-btn">
    </button>
  </ng-template>
</p-dialog>

// app/components/groceries/GroceryDeleteModal.tsx
'use client';

import { Dialog } from 'primereact/dialog';
import { Button } from 'primereact/button';
import { GroceryItem } from '../../types';

interface GroceryDeleteModalProps {
  grocery: GroceryItem;
  visible: boolean;
  onHide: () => void;
  onConfirm: (grocery: GroceryItem) => void;
}

export default function GroceryDeleteModal({
  grocery,
  visible,
  onHide,
  onConfirm,
}: GroceryDeleteModalProps) {
  const handleConfirm = () => {
    onConfirm(grocery);
    onHide();
  };

  const footer = (
    <div>
      <Button label="Cancel" onClick={onHide} severity="secondary" />
      <Button label="Delete" onClick={handleConfirm} severity="danger" />
    </div>
  );

  return (
    <Dialog
      header="Confirm Delete"
      visible={visible}
      style={{ width: '400px' }}
      onHide={onHide}
      footer={footer}
      modal
      draggable={false}
      resizable={false}
    >
      <div>
        <p>
          Are you sure you want to delete <strong>{grocery?.name}</strong>?
        </p>
        <p style={{ color: '#ef4444' }}>This action cannot be undone.</p>
      </div>
    </Dialog>
  );
}
